// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvlldeddjdkelyacjojx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2bGxkZWRkamRrZWx5YWNqb2p4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQzMDU4NzAsImV4cCI6MjA0OTg4MTg3MH0.Xo3N3psD95vq__fuEqHtNLFMVYmnS4yGy54Iy9pemt4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);